/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        'cj-verde': '#2D6A52',
        'cj-verde-light': '#3D8B6E',
        'cj-verde-dark': '#1F4E3D',
        'cj-verde-pale': '#EAF4EF',
        'cj-areia': '#F5EFE6',
        'cj-terracota': '#C8623A',
        'cj-cobre': '#D4845A',
        'cj-terra': '#3C2E28',
        'cj-cinza': '#6B6560',
        'cj-branco': '#FDFAF7',
        'cj-border': '#E0D9D1',
        'cj-sucesso': '#2D7A4F',
        'cj-aviso': '#C88A2D',
        'cj-sidebar': '#1A2E26',

        primary: '#2D6A52',
        'primary-container': '#3D8B6E',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'primary-fixed': '#EAF4EF',
        'on-primary-fixed': '#2D6A52',
        'primary-fixed-dim': '#D4E8DF',
        'on-primary-fixed-variant': '#1F4E3D',
        'inverse-primary': '#A8D5BF',

        secondary: '#C8623A',
        'secondary-container': '#EAF4EF',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#2D6A52',
        'secondary-fixed': '#F5EFE6',
        'on-secondary-fixed': '#3C2E28',
        'secondary-fixed-dim': '#E8DDD0',
        'on-secondary-fixed-variant': '#9A4A28',

        tertiary: '#D4845A',
        'tertiary-container': '#F5EFE6',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#3C2E28',
        'tertiary-fixed': '#F5EFE6',
        'on-tertiary-fixed': '#3C2E28',
        'on-tertiary-fixed-variant': '#6B6560',

        error: '#C8623A',
        'error-container': '#FFF3EE',
        'on-error': '#ffffff',
        'on-error-container': '#9A4A28',

        surface: '#FDFAF7',
        background: '#F5EFE6',
        'on-surface': '#3C2E28',
        'on-surface-variant': '#6B6560',
        'on-background': '#3C2E28',
        'surface-dim': '#E8E0D6',
        'surface-bright': '#FDFAF7',
        'surface-container-lowest': '#FDFAF7',
        'surface-container-low': '#EAF4EF',
        'surface-container': '#FDFAF7',
        'surface-container-high': '#EAF4EF',
        'surface-container-highest': '#E0D9D1',
        'surface-variant': '#E0D9D1',
        'surface-tint': '#2D6A52',
        outline: '#6B6560',
        'outline-variant': '#E0D9D1',
        'inverse-surface': '#1A2E26',
        'inverse-on-surface': '#EAF4EF',
        'warm-beige': '#F5EFE6',
      },
      backgroundImage: {
        'cj-grad': 'linear-gradient(135deg, #2D6A52 0%, #1F4E3D 60%, #3D8B6E 100%)',
        'cj-grad-warm': 'linear-gradient(135deg, #3D8B6E 0%, #2D6A52 50%, #1F4E3D 100%)',
        'cj-grad-card': 'linear-gradient(145deg, #EAF4EF 0%, #F5EFE6 100%)',
      },
      borderRadius: {
        '2xl': '1.5rem',
      },
      spacing: {
        'stack-sm': '0.5rem',
        base: '8px',
        'stack-md': '1rem',
        'container-padding-desktop': '2.5rem',
        'container-padding-mobile': '1.25rem',
        'stack-lg': '2rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        sans: ['"DM Sans"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
        display: ['"DM Serif Display"', 'Georgia', 'serif'],
        'headline-xl': ['"DM Sans"', 'sans-serif'],
        'body-lg': ['"DM Sans"', 'sans-serif'],
        'body-md': ['"DM Sans"', 'sans-serif'],
        'headline-md': ['"DM Sans"', 'sans-serif'],
        'headline-lg': ['"DM Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"DM Sans"', 'sans-serif'],
        'label-sm': ['"DM Sans"', 'sans-serif'],
        'label-md': ['"DM Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      boxShadow: {
        'cj-sm': '0 1px 4px rgba(44,68,52,.07), 0 2px 12px rgba(44,68,52,.06)',
        'cj-md': '0 4px 20px rgba(44,68,52,.10), 0 1px 4px rgba(44,68,52,.06)',
      },
    },
  },
  plugins: [],
};
