/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#e4f3fe',
        'surface-container-high': '#dbeaf5',
        'surface-tint': '#005faf',
        'on-primary-fixed-variant': '#004786',
        'on-error': '#ffffff',
        'surface-container-low': '#e9f5ff',
        'on-secondary-fixed': '#002107',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'surface-dim': '#cddce7',
        'on-error-container': '#93000a',
        'primary-fixed': '#d4e3ff',
        'on-tertiary-fixed': '#1e1b13',
        'primary-container': '#1976d2',
        'secondary-container': '#abf4ac',
        'on-surface': '#0f1d25',
        'primary-fixed-dim': '#a5c8ff',
        'surface-container-highest': '#d6e5ef',
        tertiary: '#615c51',
        'secondary-fixed': '#abf4ac',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#e1f0fb',
        outline: '#717783',
        'on-secondary-fixed-variant': '#07521d',
        'on-secondary-container': '#2e7238',
        error: '#ba1a1a',
        'on-primary-container': '#fffdff',
        'on-tertiary-container': '#fffdff',
        'on-tertiary-fixed-variant': '#4b463c',
        'tertiary-fixed': '#e9e2d3',
        'outline-variant': '#c1c6d4',
        'on-primary-fixed': '#001c3a',
        'on-primary': '#ffffff',
        surface: '#f5faff',
        background: '#f5faff',
        'on-surface-variant': '#414752',
        secondary: '#286b33',
        'tertiary-container': '#7a7569',
        'surface-bright': '#f5faff',
        'inverse-surface': '#24323a',
        'surface-variant': '#d6e5ef',
        'on-background': '#0f1d25',
        'inverse-primary': '#a5c8ff',
        primary: '#005dac',
        'secondary-fixed-dim': '#90d792',
        'on-secondary': '#ffffff',
        'warm-beige': '#FDF5E6',
      },
      borderRadius: {
        '2xl': '1.5rem',
      },
      spacing: {
        'stack-sm': '0.5rem',
        base: '8px',
        'stack-md': '1rem',
        'container-padding-desktop': '2.5rem',
        'container-padding-mobile': '1.25rem',
        'stack-lg': '2rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
